import React, { useState } from 'react'
import { useAllItineraries } from '../hooks/useAllItineraries'
import ItineraryCard from '../components/dashboard/ItineraryCard'
import ShareModal from '../components/dashboard/ShareModal'

const MyTrips = () => {
  const { data: itineraries, isLoading } = useAllItineraries()
  const [activeShareTrip, setActiveShareTrip] = useState(null)
  const [searchQuery, setSearchQuery] = useState('')

  const allItineraries = itineraries?.data?.itineraries || []

  // Filter itineraries based on search query
  const filteredItineraries = allItineraries.filter(item => {
    const term = searchQuery.toLowerCase()
    return (
      (item.to && item.to.toLowerCase().includes(term)) ||
      (item.location && item.location.toLowerCase().includes(term)) ||
      (item.itineraryData?.tripSummary && item.itineraryData.tripSummary.toLowerCase().includes(term))
    )
  })

  return (
    <div className="flex flex-col gap-8 pb-12">
      {/* Header and Search Bar */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4">
        <div>
          <h1 className="font-display-lg text-4xl font-extrabold text-on-surface mb-1">My Trips</h1>
          <p className="text-on-surface-variant text-sm">
            Manage and view all your travel itineraries generated by TripGenie.
          </p>
        </div>

        {/* Search input */}
        <div className="relative max-w-sm w-full">
          <span className="material-symbols-outlined absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant text-lg">
            search
          </span>
          <input
            type="text"
            placeholder="Search by destination..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full bg-white/70 border border-outline-variant/30 rounded-full py-2.5 pl-10 pr-4 text-sm focus:outline-none focus:border-primary focus:bg-white focus:ring-2 focus:ring-primary/10 transition-all duration-300 shadow-sm"
          />
        </div>
      </div>

      {/* Grid of Itineraries */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        {isLoading ? (
          // Skeleton Loader Grid
          [1, 2, 3].map((i) => (
            <div key={i} className="bg-white rounded-20px overflow-hidden shadow-md border border-outline-variant/10 animate-pulse flex flex-col h-full">
              <div className="h-56 w-full bg-surface-variant/40"></div>
              <div className="p-6 flex-1 flex flex-col gap-4">
                <div className="h-6 w-1/3 bg-surface-variant/40 rounded"></div>
                <div className="h-4 w-full bg-surface-variant/40 rounded"></div>
                <div className="h-4 w-2/3 bg-surface-variant/40 rounded mt-auto"></div>
              </div>
            </div>
          ))
        ) : filteredItineraries.length > 0 ? (
          filteredItineraries.map((item) => (
            <ItineraryCard
              key={item._id}
              id={item._id}
              title={item.to ? `${item.to} Journey` : 'Custom Getaway'}
              description={item.itineraryData?.tripSummary || 'Detailed AI travel itinerary by TripGenie.'}
              dates={item.date || 'Dates TBD'}
              location={item.location || item.to || 'Explore'}
              image={item.destinationImage || null}
              status="Upcoming"
              actionText="View Itinerary"
              shareId={item.shareId}
              onShare={setActiveShareTrip}
            />
          ))
        ) : (
          // Empty State
          <div className="col-span-full py-20 px-6 flex flex-col items-center justify-center text-center bg-white/50 backdrop-blur-md rounded-20px border border-outline-variant/30 shadow-sm">
            <span className="material-symbols-outlined text-6xl text-primary/30 mb-4" style={{ fontVariationSettings: "'wght' 200" }}>
              {searchQuery ? 'search_off' : 'map_search'}
            </span>
            <h3 className="font-display-lg text-2xl font-bold text-on-surface mb-2">
              {searchQuery ? 'No matching trips' : 'No itineraries generated yet'}
            </h3>
            <p className="text-on-surface-variant text-sm max-w-sm">
              {searchQuery
                ? `We couldn't find any trips matching "${searchQuery}". Try a different search term.`
                : 'Your generated itineraries will show up here. Go to the Home screen and upload your travel files to start.'}
            </p>
          </div>
        )}
      </div>

      {activeShareTrip && (
        <ShareModal
          trip={activeShareTrip}
          onClose={() => setActiveShareTrip(null)}
        />
      )}
    </div>
  )
}

export default MyTrips
